version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "13001:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
      - WECHAT_TOKEN=${WECHAT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - ${SYS_BASE_DIR:-.}/volumes/redis:/data


networks:
  default:
    name: wxlogin
